// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmmitzjqwxiwiklqkonh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtbWl0empxd3hpd2lrbHFrb25oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NjY5MjcsImV4cCI6MjA1OTU0MjkyN30.Ex8agi3lgr6-tC-l3gKTa2By75cAuwgLvu95SlwGiqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
